export const experienceData = [
    {
        role: 'Solution Architect & Senior Software Engineer',
        company: 'IT Agency of the Ministry of IDPs, Labour, Health and Social Affairs of Georgia',
        period: '2025 - CURRENT',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Lead enterprise architecture design for mission-critical government systems serving 3.7M citizens, ensuring 99.99% uptime and GDPR compliance',
            'Architect cloud-native solutions using Azure/AWS, implementing microservices architecture with event-driven patterns for scalable public services',
            'Design and govern .NET 8 ecosystem adoption across 15+ development teams, establishing architectural standards and best practices',
            'Spearhead digital transformation initiatives integrating AI/ML capabilities for intelligent document processing and citizen service automation',
            'Implement Zero Trust security architecture with multi-layered defense strategies, achieving SOC 2 Type II compliance',
            'Orchestrate DevSecOps pipelines with automated security scanning, reducing deployment time by 60% while maintaining security standards',
            'Mentor cross-functional teams of 20+ engineers on Clean Architecture, Domain-Driven Design, and SOLID principles',
            'Drive technical strategy for API-first ecosystem with comprehensive OpenAPI specifications serving 200+ government integrations',
            'Champion performance optimization initiatives achieving sub-100ms response times for critical public-facing services',
            'Establish observability frameworks with distributed tracing, metrics collection, and real-time alerting using ELK stack and Grafana',
        ],
        technologies: [
            '.NET 8',
            'Azure',
            'AWS',
            'Microservices',
            'Clean Architecture',
            'DDD',
            'CQRS/Event Sourcing',
            'Kubernetes',
            'Docker',
            'Redis',
            'RabbitMQ',
            'PostgreSQL',
            'Entity Framework Core',
            'Identity Server',
            'OAuth 2.0/JWT',
            'CI/CD',
            'Terraform',
        ],
    },
    {
        role: 'Senior Backend Engineer',
        company: 'Credo Bank',
        period: '10/2024 - 01/2025',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Architected high-throughput banking APIs processing 500K+ daily transactions with 99.95% availability SLA',
            'Designed event-driven microservices architecture enabling real-time payment processing and fraud detection systems',
            'Implemented sophisticated caching strategies using Redis, reducing database load by 70% and improving response times to <50ms',
            'Built resilient distributed systems with circuit breakers, retry policies, and graceful degradation patterns using Polly',
            'Optimized SQL Server performance through advanced query optimization, achieving 10x faster transaction processing',
            'Established comprehensive API governance with rate limiting, versioning strategies, and backward compatibility protocols',
            'Led migration from monolithic architecture to microservices, improving deployment frequency from monthly to daily releases',
            'Implemented financial-grade security with PCI DSS compliance, encryption at rest/transit, and audit logging',
        ],
        technologies: [
            'ASP.NET Core',
            'C#',
            'Microservices',
            'Event-Driven Architecture',
            'Entity Framework Core',
            'Dapper',
            'Redis',
            'OAuth 2.0/JWT',
            'Azure DevOps',
            'SQL Server',
            'Docker',
            'Kubernetes',
        ],
    },
    {
        role: 'Senior .NET Developer',
        company: 'Procredit Bank',
        period: '11/2023 - 02/2025',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Spearheaded PSD2 Open Banking API implementation serving 50+ fintech partners with 99.9% uptime',
            'Architected OAuth 2.0/OpenID Connect authentication flows ensuring bank-grade security for third-party integrations',
            'Designed and implemented CQRS pattern with MediatR for complex financial transaction processing',
            'Built distributed caching layer with Redis for high-frequency balance inquiries, handling 10M+ daily requests',
            'Implemented comprehensive monitoring and alerting using Application Insights and custom telemetry',
            'Established automated testing strategy with 90%+ code coverage using xUnit, NSubstitute, and integration tests',
            'Led API documentation initiatives with detailed Swagger/OpenAPI specs accelerating partner onboarding by 40%',
            'Optimized database schemas and queries, reducing transaction processing time from 2s to 200ms',
            'Championed DevOps culture implementing GitOps workflows with automated deployments and rollback capabilities',
        ],
        technologies: [
            '.NET Core',
            'C#',
            'Microservices',
            'PSD2/Open Banking',
            'CQRS/MediatR',
            'OAuth 2.0/OIDC',
            'Redis',
            'SQL Server',
            'Docker',
            'Azure DevOps',
            'Application Insights',
            'xUnit',
        ],
    },
    {
        role: 'Full Stack .NET Developer',
        company: 'NovaSystems',
        period: '10/2020 - 01/2025',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Architected AI-powered candidate matching system using ML.NET, reducing recruitment time by 40% and improving match accuracy to 85%',
            'Built enterprise-grade RESTful APIs serving 100K+ monthly users across multiple client applications',
            'Engineered automated workflow solutions saving 72+ hours monthly through intelligent business process optimization',
            'Designed responsive full-stack applications using ASP.NET Core MVC with modern JavaScript frameworks (React, Vue)',
            'Successfully delivered 200+ features while maintaining high code quality standards and meeting aggressive delivery timelines',
            'Optimized database performance through advanced indexing and query refinement, achieving 30% performance improvement',
            'Implemented comprehensive logging, monitoring, and alerting infrastructure ensuring 99.9% application availability',
            'Mentored 5+ junior developers on software craftsmanship, design patterns, and professional development practices',
            'Collaborated with product owners to define technical roadmaps and translate business objectives into engineering solutions',
            'Established CI/CD best practices with automated testing and deployment pipelines using Azure DevOps',
        ],
        technologies: [
            'C#',
            'ASP.NET Core',
            'ASP.NET MVC',
            'MS SQL Server',
            'Entity Framework',
            'JavaScript/TypeScript',
            'React',
            'RESTful APIs',
            'Azure DevOps',
            'Git',
        ],
    },
    {
        role: '.NET Web Developer',
        company: 'IBOSS',
        period: '2020 - 2023',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Developed high-performance IMEI verification platform handling 50K+ daily verifications with sub-10 second response times',
            'Integrated payment processing for major providers (VISA, Mastercard, AMEX, Apple Pay) achieving PCI DSS Level 1 compliance',
            'Built mobile-first responsive interfaces with 98% cross-device compatibility across iOS and Android platforms',
            'Designed secure RESTful APIs enabling B2B integrations with 20+ third-party partners and resellers',
            'Optimized database architecture to efficiently process high-volume transactions with consistent performance',
            'Implemented comprehensive security framework including AES-256 encryption, secure session management, and OWASP Top 10 mitigation',
            'Established automated QA processes with unit and integration testing reducing production defects by 60%',
            'Created detailed technical documentation and API specifications accelerating new developer onboarding',
            'Collaborated with UX designers to implement conversion-optimized checkout flows increasing completion rates by 25%',
            'Managed full SDLC from requirements gathering through deployment and ongoing maintenance',
        ],
        technologies: [
            'ASP.NET MVC',
            '.NET Web API',
            'C#',
            'JavaScript/jQuery',
            'HTML5/CSS3',
            'SQL Server',
            'Payment Gateway Integration',
            'PCI DSS',
            'Responsive Design',
            'REST APIs',
            'Security',
        ],
    },
];