export const experienceData = [
    {
        role: 'Software developer',
        company: 'IT Agency of the Ministry of IDPs, Labour, Health and Social Affairs of Georgia',
        period: '2025 - CURRENT',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Architected and implemented high-security backend systems for critical government services using .NET 8, C#, and Clean Architecture principles',
            'Designed and developed enterprise applications following CQRS and Mediator patterns to ensure separation of concerns and maintainable codebase',
            'Engineered scalable RESTful APIs with minimal latency to facilitate seamless data exchange between ministerial departments and external stakeholders',
            'Implemented comprehensive domain-driven design solutions to address complex business requirements in public administration',
            'Developed optimized database solutions using Entity Framework Core with performance-tuned queries for handling sensitive citizen data',
            'Established secure authentication and authorization protocols using Identity Server 4 and JWT to protect confidential government information',
            'Created robust logging and monitoring systems to ensure traceability and accountability for all system operations',
            'Led technical decision-making for critical infrastructure projects, balancing innovation with government security requirements',
            'Collaborated with cross-functional teams to translate complex regulatory requirements into maintainable software solutions',
        ],
        technologies: [
            '.NET 8',
            'C#',
            'ASP.NET Core',
            'Entity Framework Core',
            'Clean Architecture',
            'CQRS',
            'Mediator',
            'Identity Server 4',
            'JWT',
            'SQL Server',
            'Domain-Driven Design',
        ],
    },
    {
        role: 'Software developer',
        company: 'Credo Bank',
        period: '10/2024 - 01/04/2025',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Architected and implemented RESTful APIs using ASP.NET Core and C# following industry best practices and SOLID principles',
            'Designed and developed microservices architecture to ensure scalability, maintainability, and fault tolerance',
            'Engineered efficient data access patterns utilizing Entity Framework Core and Dapper ORM for optimal performance',
            'Implemented advanced security features including OAuth 2.0, JWT authentication, and role-based access control',
            'Orchestrated CI/CD pipelines using Azure DevOps, automating build, test, and deployment processes',
            'Optimized database performance through query tuning, indexing strategies, and stored procedure refinement',
            'Collaborated with cross-functional teams to translate business requirements into technical specifications',
            'Documented APIs using Swagger/OpenAPI specification to facilitate integration with third-party systems',
        ],
        technologies: [
            'ASP.NET Core',
            'C#',
            'Microservices',
            'Entity Framework Core',
            'Dapper',
            'OAuth 2.0',
            'JWT',
            'Azure DevOps',
            'CI/CD',
            'SQL Server',
            'Swagger/OpenAPI',
        ],
    },
    {
        role: 'Software developer',
        company: 'Procredit Bank',
        period: '11/2023 - 02/2025',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Designing and developing RESTful APIs to comply with PSD2 regulations and Open Banking standards',
            'Implementing secure authentication protocols and data exchange mechanisms for third-party integrations',
            'Maintaining and optimizing microservices architecture using .NET Core and C#',
            'Collaborating with front-end teams to ensure seamless integration with banking applications',
            'Developing robust error handling and logging systems to maintain service reliability',
            'Creating comprehensive unit and integration tests to ensure code quality',
            'Participating in code reviews and implementing best practices for secure financial software development',
            'Managing database interactions and optimizing queries for performance',
            'Contributing to CI/CD pipeline improvements for faster and more reliable deployments',
            'Documenting APIs and technical solutions for internal and external stakeholders',
        ],
        technologies: [
            '.NET Core',
            'C#',
            'Microservices',
            'PSD2',
            'Open Banking',
            'RESTful APIs',
            'CI/CD',
            'Unit Testing',
            'SQL',
            'Authentication',
            'Security',
        ],
    },
    {
        role: 'Software developer',
        company: 'NovaSystems',
        period: '10/2020 - 01/04/2025',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Engineered an advanced matching algorithm in MS SQL for an HR Recruitment Agency System, automating candidate screening and reducing selection time by 40%',
            'Developed and maintained RESTful APIs for GAMAGAS.GE using C# and ASP.NET Core, implementing security best practices and comprehensive documentation',
            'Created efficiency-focused software solutions that eliminated 18+ hours of monthly manual work through intelligent automation and process optimization',
            'Designed and implemented scalable full-stack applications leveraging ASP.NET MVC architecture and modern JavaScript frameworks',
            'Delivered over 200 high-quality development tasks while maintaining strict code standards and meeting aggressive deadlines',
            'Performed complex SQL query optimization and database tuning, resulting in 30% improved application performance',
            'Established comprehensive error handling protocols and monitoring systems to ensure 99.9% uptime in production environments',
            'Conducted thorough code reviews and mentored junior developers on C# best practices and design patterns',
            'Collaborated with business stakeholders to translate requirements into technical specifications and implementation roadmaps',
            'Implemented CI/CD pipelines to streamline deployment processes and ensure reliable software delivery',
        ],
        technologies: [
            'C#',
            'ASP.NET Core',
            'ASP.NET MVC',
            'MS SQL',
            'JavaScript',
            'RESTful APIs',
            'SQL Optimization',
            'CI/CD',
            'Error Handling',
            'Mentoring',
        ],
    },
    {
        role: 'Web developer',
        company: 'IBOSS',
        period: '2020 - 2023',
        location: 'Tbilisi, Georgia',
        responsibilities: [
            'Architected and developed a comprehensive IMEI verification platform with response times under 10 seconds, utilizing HTML, CSS, jQuery for front-end and ASP.NET MVC for back-end',
            'Implemented secure payment gateway integrations with major providers (VISA, Mastercard, AMEX, Apple Pay), ensuring PCI DSS compliance throughout the application',
            'Engineered a modern, responsive user interface optimized for both iPhone and Samsung smartphone users, significantly improving user experience and satisfaction',
            'Designed and built RESTful APIs enabling seamless third-party integrations and data exchange using .NET Web API',
            'Developed robust database schemas and optimized queries to handle high-volume transaction processing efficiently',
            'Created comprehensive logging and error handling systems to ensure application stability and facilitate troubleshooting',
            'Implemented end-to-end security measures including data encryption, secure authentication, and authorization protocols',
            'Established automated testing procedures to maintain code quality and prevent regression issues',
            'Collaborated with cross-functional teams to translate business requirements into technical specifications and solutions',
            'Participated in all phases of the software development lifecycle from initial planning to deployment and maintenance',
        ],
        technologies: [
            'HTML',
            'CSS',
            'jQuery',
            'ASP.NET MVC',
            '.NET Web API',
            'IMEI verification',
            'Payment gateways',
            'PCI DSS',
            'Responsive design',
            'Database optimization',
            'Security',
        ],
    },
];